### ISSUE TITLE
Problem during compilation with exercises in lesson 5

### ISSUE THREAD

**Issue by amolinafw** [NordicDeveloperAcademy/wifi-fund#2]
Hi, I am having this error during compilation with all the examples in lesson 5:
#error "PSA_WANT_ALG_DETERMINISTIC_ECDSA defined, but not all prerequisites"
I am using the solutions and in the build configuration I am using nrf5340dk_nrf5340_cpuapp_ns with the extra CMake argument -DSHIELD=nrf7002ek. My SDK version is v2.6.1 and my toolchain version is v2.5.2. It is happening with all the examples in the lesson 5. Thanks in advance.

**Comment by heidisollie** [comment]
Hi, I am not able to reproduce the error you're describing, with the same environment (SDK version v2.6.1, toolchain version v2.5.2). Could you please make a ticket on DevZone (https://devzone.nordicsemi.com/support/add) for this issue? Thanks!

**Comment by amolinafw** [comment]
Thank you for the reply. I will use this link, probably I have a misconfiguration in my project.
